### ISSUE TITLE
[bug] The right-click hide occasionally fails

### ISSUE THREAD

**Issue by Cattle0Horse** [bomian98/obsidian-hide-commands-in-menu#1]
The demonstration is as follows:
![Image](https://github.com/user-attachments/assets/f88a3fd1-23bf-4ddf-9e1b-8fc56191d2aa)
The settings are as follows:
![Image](https://github.com/user-attachments/assets/910dd6c0-11f5-4066-a0df-66144064196a)

**Comment by bomian98** [comment]
从设计角度来说，不是失败。而是当前的实现方式是，在菜单显示出来的 1ms 后，针对显示的菜单项进行判断，移除需要隐藏的内容。当前我没有想到更好的办法了，Obsidian 插件程序库中没有直接的办法能提前去隐藏，只提供了添加的方法，没有删除的方法。

插件还处于 review 状态，待 Obsidian 开发者 review 后，看看有没有更好的办法。

**Comment by bomian98** [comment]
@Cattle0Horse 对，我知道这个插件。
这个插件和原生的 https://github.com/kzhovn/obsidian-customizable-menu 逻辑是一样的，在 https://github.com/Mara-Li/obsidian-context-menu-hider/blob/669f8d49a9513b2d05495a7b2ea5282fd5ade8f6/src/main.ts#L16C8-L16C21 中调用 MenuItem 的 setTitle 的时候，对于每个菜单项判断是否要被删除。如果要被删除，则增加一个 css class，并通过 css 进行隐藏。

如果依旧按照原生的 obsidian-customizable-menu 逻辑，那么实现方式我能想到的是这样的：

1. 首先，依旧是 MenuItem 的 setTitle，判断当前 menu item 的文本是否在某个要删除的菜单类中，如果是，添加对应菜单类的 css class，比如你这个是 editor-menu-hide-item class。
2. 其次，给每个菜单注入对应的 css class，比如这个注入的是 editor-menu class。
3. 在 css 样式文件中，为每个菜单要隐藏的配置 css 样式。

```css
.editor-menu .editor-menu-hide-item {
  display: none;
}

.url-menu .url-menu-hide-item {
  display: none;
}

.file-menu-link .file-menu-link-hide-item {
  display: none;
}

// .....
```

这样之后，基本功能能实现。这个我之前考虑过了，不过这样没有办法对多余的分割线进行分割。就比如说，tab 右键后，有很多分割线，去除两个分割线内所有菜单项后，会显得分割线多余，但不能通过 css 自动去除多余分割线（我对前端不太熟，问了 gpt 是不能）。

**Comment by Flyingfolder** [comment]
> [@Cattle0Horse](https://github.com/Cattle0Horse) 对，我知道这个插件。 这个插件和原生的 https://github.com/kzhovn/obsidian-customizable-menu 逻辑是一样的，在 https://github.com/Mara-Li/obsidian-context-menu-hider/blob/669f8d49a9513b2d05495a7b2ea5282fd5ade8f6/src/main.ts#L16 中调用 MenuItem 的 setTitle 的时候，对于每个菜单项判断是否要被删除。如果要被删除，则增加一个 css class，并通过 css 进行隐藏。
> 
> 如果依旧按照原生的 obsidian-customizable-menu 逻辑，那么实现方式我能想到的是这样的：
> 
> 1. 首先，依旧是 MenuItem 的 setTitle，判断当前 menu item 的文本是否在某个要删除的菜单类中，如果是，添加对应菜单类的 css class，比如你这个是 editor-menu-hide-item class。
> 2. 其次，给每个菜单注入对应的 css class，比如这个注入的是 editor-menu class。
> 3. 在 css 样式文件中，为每个菜单要隐藏的配置 css 样式。
> 
> .editor-menu .editor-menu-hide-item {
>   display: none;
> }
> 
> .url-menu .url-menu-hide-item {
>   display: none;
> }
> 
> .file-menu-link .file-menu-link-hide-item {
>   display: none;
> }
> 
> // .....
> 这样之后，基本功能能实现。这个我之前考虑过了，不过这样没有办法对多余的分割线进行分割。就比如说，tab 右键后，有很多分割线，去除两个分割线内所有菜单项后，会显得分割线多余，但不能通过 css 自动去除多余分割线（我对前端不太熟，问了 gpt 是不能）。


---

使用 css 是可以自动去除多余的分割线的。（无意挖坟哈，只是为插件开发提供一些思路。作者大大可以随时采纳 or 不采纳。（PS：我是js小白，写不来插件orz. PPS：如果有需要，我可以去单开一个issue）

这一组 css 可以用来「当用 js 标记时，如果`.menu-group` 的子元素全部被隐藏掉，那么把后面的 `.menu-seperator`也隐藏掉 」

```css
/* 默认状态下，隐藏掉 seperator */
.menu-group + .menu-separator {
    display: none;
}
/* 如果存在 menu-item 还没被隐藏，那么就显示 menu seperator */
.menu-group:has(.menu-item:not(.is-hidden)) + .menu-separator {
    display: block; 
}
```

---

当然，也可以把 `.is-hidden` 类换成 `.is-visible` 类，对应的 css 就变成了

```css
.menu-group + .menu-separator {
    display: none;
}
.menu-group:has(.menu-item.is-visible) + .menu-separator {
    display: block; 
}
```
